Environment:
  size_range:
    - length_range: [ 20, 30 ]
    - width_range: [ 20, 30 ]

  Style:
    - pretty_mode: False

  random_seed: 42
  rules:
    - MinAllDistance:
        - distance: 1.0

  Borders:
    - xml_name: "Border.xml"
    - place: True
    - object: Hedge
  Objects:
    Tree:
      - xml_name: "Tree.xml"
      - amount: [ 1, 3 ]
      - distribution: Normal
      - type: container
      - tags: [ "Tree", "Obstacle" ]
      - rules:
          - MinObjectDistance:
              - distance: 1.5
              - object: Tree
          - MinAllDistance:
              - distance: 1.0

    Stone:
      - xml_name: "Stone.xml"
      - amount: 1
      - coordinates: [ [10, 10, 10] ]
      - type: collectable
      - tags: [ "Stone" ]

    Apple:
      - xml_name: "Apple.xml"
      - amount: [ 10, 10 ]
      - type: collectable
      - tags: [ "Apple" ]
      - random_attributes:
          - colors: [ 5, 5 ]
          - sizes: [ 5, 10 ]
Areas:
  Area1:
    size: small
    rules:
      - MinAllDistance:
          - distance: 1.5
    Objects:
      Tree:
        - xml_name: "Tree.xml"
        - amount: [ 1, 3 ]
        - type: container
        - variants: [ "Kiefer", "Buche", "Eiche" ]

      Stone:
        - xml_name: "Stone.xml"
        - amount: [ 1, 2 ]
        - type: obstacle

      Apple:
        - xml_name: "Apple.xml"
        - amount: [ 1, 1 ]
        - type: attachable
        - attaches: [ Tree ]

  Area2:
    size: small
    Objects:
      Tree:
        - xml_name: "Tree.xml"
        - amount: [ 1, 2 ]
        - type: container

      Stone:
        - xml_name: "Stone.xml"
        - amount: [ 1, 1 ]
        - type: obstacle

      Apple:
        - xml_name: "Apple.xml"
        - amount: [ 1, 2 ]
        - type: attachable_item
        - attaches: [ Tree ]
