#  Agent:
#    - amount: 2
#    - position: [(10, 10), (50, 50)]

Environment:
  size: [ 100, 100 ]
  random_seed: 42
  rules:
    - MinAllDistance:
        - distance: 1.0

  Borders:
    - place: True
    - object: Hedge
  Objects:
    Tree:
      - amount: [ 1, 3 ]
      - distribution: Normal
      - type: container
      - tags: [ "Tree", "Obstacle" ]
      - rules:
          - MinObjectDistance:
              - distance: 1.5
              - object: Tree
          - MinAllDistance:
              - distance: 1.0

    Stone:
      - coordinate: [ 10, 10 ]
      - type: collectable
      - tags: [ "Stone" ]

    Apple:
      - amount: [ 10, 10 ]
      - type: collectable
      - tags: [ "Apple" ]
      - random_attributes:
          - colors: [ 5, 5 ]
          - sizes: [ 5, 10 ]
Areas:
  Area1:
    size: small
    Objects:
      Tree:
        - amount: [ 1, 3 ]
        - type: container
        - variants: [ "Kiefer", "Buche", "Eiche" ]

      Stone:
        - amount: [ 1, 2 ]
        - type: obstacle

      Apple:
        - amount: [ 1, 1 ]
        - type: attachable
        - attaches: [ Tree ]

  Area2:
    size: small
    Objects:
      Tree:
        - amount: [ 1, 2 ]
        - type: container

      Stone:
        - amount: [ 1, 1 ]
        - type: obstacle

      Apple:
        - amount: [ 1, 2 ]
        - type: attachable_item
        - attaches: [ Tree ]
