Environment:
  size: [10, 10]
  Borders:
    - place: True
    #- type: Hecke

Areas:
  Area1:
    size: small
    Objects:
      Tree:
      - amount: [10, 20]
      - type: container
      #- variants: ["Kiefer", ] # [kiefer,buche,...]

      Stone:
      - amount: [10, 10]
      - type: obstacle

      Apple:
      - amount: [5, 8]
      - type: attachable_item
      - attaches: [Tree]
